<?php
session_start();
if (!isset($_SESSION['first_name'])) {
    header("Location: ../index.php");
    exit();
}

$db = new mysqli("localhost", "root", "", "pos_system");
if ($db->connect_error) die("Connection failed: " . $db->connect_error);

// Fetch all transactions
$transactions = $db->query("
    SELECT t.transaction_id, t.sale_date, t.user_id, u.first_name, u.last_name,
           t.product_id, p.name AS product_name, t.quantity, t.total_price
    FROM transactions t
    JOIN users u ON t.user_id = u.user_id
    JOIN products p ON t.product_id = p.product_id
    ORDER BY t.sale_date DESC
");

// Summary totals
$stats = $db->query("
    SELECT COUNT(*) AS total_transactions, SUM(quantity) AS total_items, SUM(total_price) AS total_sales
    FROM transactions
")->fetch_assoc();

// ✅ NEW: Sales summary by product
$sales_summary = $db->query("
    SELECT p.name AS product_name, p.price, 
           SUM(t.quantity) AS units_sold, 
           SUM(t.total_price) AS total_sales
    FROM transactions t
    JOIN products p ON t.product_id = p.product_id
    GROUP BY p.product_id, p.name, p.price
    ORDER BY total_sales DESC
");
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Inventory Report</title>
<style>
@page { size: 40mm auto; margin: 0; }
body {
    font-family: 'Courier New', monospace;
    font-size: 10px;
    color: #000;
    font-weight: bold;
    margin: 0;
}
#receipt {
    width: 40mm;
    padding: 3px;
}
h3, p {
    text-align: center;
    margin: 2px 0;
    font-weight: bold;
}
hr {
    border: none;
    border-top: 1px dashed #000;
    margin: 3px 0;
}
table {
    width: 100%;
    border-collapse: collapse;
    font-size: 9px;
    font-weight: bold;
}
th, td {
    padding: 1px 0;
    font-weight: bold;
}
td.right {
    text-align: right;
}
td.center {
    text-align: center;
}
.section-title {
    text-align: center;
    font-weight: bold;
    border-top: 1px solid #000;
    border-bottom: 1px solid #000;
    margin: 4px 0;
    padding: 2px 0;
}
.footer {
    text-align: center;
    font-size: 9px;
    font-weight: bold;
    margin-top: 5px;
}
</style>
</head>
<body>
<div id="receipt">
    <h3>TWIN BITES SNACK CORNER</h3>
    <p>Kapitan Ponso St., Bauan, Batangas</p>
    <p>Tel: +639975228553</p>
    <p><?= date('Y-m-d H:i:s') ?></p>
    <hr>

    <div class="section-title">INVENTORY REPORT</div>
    <table>
        <tr>
            <th>DATE</th>
            <th class="center">ID</th>
            <th class="center">PRODUCT</th>
            <th class="right">QTY</th>
            <th class="right">TOTAL</th>
        </tr>
        <?php while($t = $transactions->fetch_assoc()): ?>
        <tr>
            <td><?= date('m-d H:i', strtotime($t['sale_date'])) ?></td>
            <td class="center"><?= $t['transaction_id'] ?></td>
            <td class="center"><?= substr($t['product_name'], 0, 10) ?></td>
            <td class="right"><?= $t['quantity'] ?></td>
            <td class="right">₱<?= number_format($t['total_price'], 0) ?></td>
        </tr>
        <?php endwhile; ?>
    </table>

    <hr>

    <!-- ✅ NEW: Sales Summary by Product -->
    <div class="section-title">SALES SUMMARY</div>
    <table>
        <tr>
            <th>PRODUCT</th>
            <th class="right">SOLD</th>
            <th class="right">PRICE</th>
            <th class="right">TOTAL</th>
        </tr>
        <?php while($s = $sales_summary->fetch_assoc()): ?>
        <tr>
            <td><?= substr($s['product_name'], 0, 10) ?></td>
            <td class="right"><?= $s['units_sold'] ?></td>
            <td class="right">₱<?= number_format($s['price'], 0) ?></td>
            <td class="right">₱<?= number_format($s['total_sales'], 0) ?></td>
        </tr>
        <?php endwhile; ?>
    </table>

    <hr>

    <!-- Totals -->
    <table>
        <tr><td>Total Transactions:</td><td class="right"><?= $stats['total_transactions'] ?? 0 ?></td></tr>
        <tr><td>Total Items:</td><td class="right"><?= $stats['total_items'] ?? 0 ?></td></tr>
        <tr><td>Total Sales:</td><td class="right">₱<?= number_format($stats['total_sales'] ?? 0, 0) ?></td></tr>
    </table>

    <hr>
    <div class="footer">
        <p>Report generated by <?= htmlspecialchars($_SESSION['first_name']) ?></p>
        <p>Thank you!</p>
    </div>
</div>

<script>
window.onload = function() {
    window.print();
    window.onafterprint = function() {
        window.location.href = 'Transactions.php';
    };
}
</script>
</body>
</html>